# -*- coding: utf-8 -*-
"""Filesize Tests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HmzUHozvjf0RU43EJmROWDFQNSt6cqI_
"""

import os
import matplotlib.pyplot as plt
from datetime import datetime

# Directory containing the WAV files
directory = r'C:\Users\aidan\Downloads\UBNA_022'

# List to store file sizes and dates
file_sizes = []
dates = []

# Iterate over files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.WAV') or filename.endswith('.wav'):
        file_path = os.path.join(directory, filename)
        file_size = os.path.getsize(file_path)

        # Extract the date portion from the filename (YYYYMMDD_TTTTTT.WAV)
        date_str = filename.split('_')[0]  # Extract YYYYMMDD part
        try:
            date = datetime.strptime(date_str, '%Y%m%d')
        except ValueError:
            print(f"Skipping file with invalid date format: {filename}")
            continue

        file_sizes.append(file_size)
        dates.append(date)

# Convert dates to ordinal values for plotting
dates_ordinal = [date.toordinal() for date in dates]

# Plot file sizes over time
plt.figure(figsize=(10, 6))
plt.plot(dates_ordinal, file_sizes, marker='o')
plt.xlabel('Date')
plt.ylabel('File Size (bytes)')
plt.title('File Size Over Time')
plt.xticks(dates_ordinal, [date.strftime('%Y-%m-%d') for date in dates], rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()